config.toml
Creating microsite: step "Customize the site to use your Github repo."
=> Update github_repo URL

.gitignore
Dependency changes, ignore build dir
=> Dependency changes, ignore build dir

content/en/_index.html, content/en/docs/_index.md
Thank you for your contribution.
=> Customize landing page and index page

config.toml, static/admin/config.js
Configuring microsite. See - https://github.com/Axway/open-docs-microsite-template#connect-your-microsite-to-the-axway-open-docs-ecosystem
=> Customize the site to use Netlify CMS instance

config.toml
More updates to change axway-open-docs to amplifystreams-open-docs
=> Update docs site naming

static/admin/config.js
deploy preview - https://deploy-preview-15--amplifystreams-open-docs.netlify.app/admin/
=> Update Streams documentation collections on CMS

README.md, config.toml, content/en/_index.html, static/admin/config.js
See https://jira.axway.com/browse/RMF-11
=> RMF-11 Update site name from amplifystreams to streams

content/en/docs/streams/install/_index.md
Fix a hyphen encoding issue and add a paragraph to explain secrets deletion in _uninstallation_ section
=> STREAMS-1418 doc(): fix hyphen encoding + add paragraĥ to delete secrets

content/en/docs/streams/architecture/_index.md, content/en/docs/streams/install/_index.md
=> Remove all reference to hazelcast

.github/workflows/merge_to_develop.yml
A new branch, `develop`, was created on Streams project. 
Now, we need a workflow/ GitHub action to automatically cherry-pick all pull requests from `master` to the `develop` branch immediately after they are merged. 
For more information, see https://github.com/Axway/axway-open-docs/pull/818/
=> RMF-42 Create workflow to merge master branch into develop branch

content/en/docs/security/security_features.md, package-lock.json, package.json
* Update security feature related database encryption.
* Refer to TLS instead of SSL.
* Remove encryption feature between streams micro services and Kafka (coming in future release).
* Bump node dependency version (autoprefixer).
=> Streams security guide

content/en/docs/subscribers/subscriber-kafka.md, content/en/docs/subscribers/subscriber-webhook.md
* Update Kafka & Webhook subscribers definitions
=> Update Kafka & Webhook subscribers definitions

content/en/docs/install/_index.md
Add documentation for Kafka security settings: SASL authentication and TLS encryption.
=> STREAMS-1237 doc(install): add documentation for Kafka security settings

content/en/docs/install/_index.md
=> STREAMS-1237 doc(install): align secret names

content/en/docs/install/_index.md
Add documentation to install Streams using an external database instead of the one provided by the Helm chart.
=> Add documentation to install Streams using an external database instead of the one provided by the Helm chart

content/en/docs/install/_index.md
Refactor the MariaDB security features part to make it clearer.
=> Make the MariaDB security features part clearer

package-lock.json, package.json
Bump postcss-cli version to fix security vulnerability on yargs-parser
=> Bump postcss-cli version to fix security vulnerability

content/en/docs/install/_index.md
adapt Kafka documentation accordingly to the Helm chart refactoring
Add documentation to install Streams using an external Kafka cluster
Adapt Kafka install documentation accordingly to the Helm chart refactoring
=> STREAMS-1504 - Install Streams using an external Kafka cluster

content/en/docs/subscribers/subscriber-webhook.md
=> STREAMS-1279 - Describe webhook exchanges API.

content/en/docs/install/_index.md
* [x ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ x] You have signed the [Axway CLA](https://cla.axway.com/)
* [x ] You have verified the technical accuracy of your change
* [x ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [x ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)
_Put an x in the boxes that apply. If you're …
=> STREAMS-1440 - Refactor Streams helm chart

content/en/docs/install/_index.md
=> STREAMS-1639 - Explain how to use helm parameters properly

content/en/docs/architecture/_index.md
=> STREAMS-1644 -  Upgrade kafka version

content/en/docs/relnotes/20210127_streams_relnotes.md, content/en/docs/relnotes/_index.md, static/admin/config.js
* Add release note section to Streams documentation
* Add release note for Streams Jan21 release
=> STREAMS-1705 Add release note section

content/en/docs/install/_index.md
=> STREAMS-1322 - Disable CORS by defaullt

content/en/docs/install/_index.md
Add missing kafka configuration option to properly disable security
=> STREAMS-1779 Add missing kafka configuration option to disable security

content/en/docs/_index.md, content/en/docs/install/_index.md, content/en/docs/install/backup-recovery.md, content/en/docs/install/helm-parameters.md, content/en/docs/install/uninstall.md, content/en/docs/install/upgrade.md, package-lock.json
Broke out Install topics:
Install (index)
Helm parameters
Upgrade
Uninstall
Backup and disaster recovery
Note: I did not address the heading issue in the install topic. I will do that next.
=> STREAMS-1597 Restructure Install

content/en/docs/metrics.md
I have added a description of the metrics provided by Streams so that users can monitor their installations
=> STREAMS-935 Add description of custom metrics available for monitoring

content/en/docs/install/_index.md, content/en/docs/install/helm-parameters.md, content/en/docs/install/uninstall.md, content/en/docs/publishers/publisher-http-poller.md, content/en/docs/publishers/publisher-http-post.md, content/en/docs/quickstart.md, content/en/docs/relnotes/20210127_streams_relnotes.md, content/en/docs/subscribers/subscriber-kafka.md, content/en/docs/subscribers/subscriber-sse.md, content/en/docs/subscribers/subscriber-webhook.md, content/en/docs/topics-api.md
In Streams 1750 api paths were changed to anticipate a need to version them. This PR is meant to include those changes in the documentation.
=> Streams 1750 - document new REST api paths

content/en/docs/install/uninstall.md, content/en/docs/relnotes/20210331_streams_relnotes.md
=> Add March21 release note

content/en/docs/architecture/_index.md, content/en/docs/install/_index.md, content/en/docs/install/helm-parameters.md
We change the Nginx Helm chart to the Bitnami Nginx Helm chart. We have to update url and parameters accrordingly.
=> STREAMS-1866 update Nginx helm chart url and parameters

content/en/docs/architecture/_index.md, content/en/docs/relnotes/20210531_streams_relnotes.md
https://deploy-preview-77--streams-open-docs.netlify.app/docs/relnotes/20210531_streams_relnotes/
=> STREAMS-1831 Upgrade kafka version and create Release Notes page for May 21 release

content/en/docs/relnotes/20210531_streams_relnotes.md
https://deploy-preview-81--streams-open-docs.netlify.app/docs/relnotes/20210531_streams_relnotes/
Streams images are now based on OpenJDK 11.0.11.
Third party Docker images have been upgraded.
=> STREAMS-1999 Migrate Streams services to OpenJDK 11.0.11

package-lock.json
RMF-177 Update postcss to a non-vulnerable version
=> RMF-177 Update postcss to a non-vulnerable version

package-lock.json
Reverts Axway/streams-open-docs#89
=> Revert "RMF-185 Update sha512 string on postcss version 8.2.10 to fix error when deploying site"

package-lock.json, package.json
=> RDAPI-24501 Update JSON packages to fix Netlify deploys

build.sh
=> RDAPI-24501 Update for when building the microsites locally

content/en/docs/install/_index.md
https://deploy-preview-93--streams-open-docs.netlify.app/docs/install/
=> STREAMS-2077 Explain how to accept the general conditions

content/en/docs/architecture/_index.md, content/en/docs/relnotes/20210618_streams_relnotes.md
Update versions of docker images used, because of liblz4 vulnerability.
https://deploy-preview-97--streams-open-docs.netlify.app/docs/architecture/
https://deploy-preview-97--streams-open-docs.netlify.app/docs/relnotes/20210618_streams_relnotes/
=> STREAMS-2084 libz4 upgrade versions of docker images and create June 2021 Release Notes

.github/pull_request_template.md
=> Update pull request template to remove checklist for approvers

.github/workflows/labeler.yml
Adding Pull Request size labeler (https://github.com/CodelyTV/pr-size-labeler) to the project.
=> Adding Pull Request size labeler to the project

content/en/docs/install/helm-parameters.md
https://deploy-preview-99--streams-open-docs.netlify.app/docs/install/helm-parameters/#streams-parameters
=> STREAMS-2088 Add missing helm parameter

content/en/docs/install/backup-recovery.md
https://deploy-preview-94--streams-open-docs.netlify.app/docs/install/backup-recovery
=> STREAMS-1921 Add Disaster Recovery Plan procedures

content/en/docs/install/backup-recovery.md, content/en/docs/metrics.md
https://deploy-preview-100--streams-open-docs.netlify.app/docs/metrics/#monitoring
Add section to document Streams metrics to monitor for Streams production installations.
=> STREAMS-1734 document Streams metrics to monitor

content/en/docs/install/_index.md, content/en/docs/install/helm-parameters.md
https://deploy-preview-102--streams-open-docs.netlify.app/docs/install/
=> STREAMS-2090 Update ingress annotations parameters and Add info about double quotation marks usage

content/en/docs/install/_index.md, content/en/docs/install/helm-parameters.md, content/en/docs/relnotes/20210618_streams_relnotes.md
=> Final review, tide up, and minor fixes in preparation for Streams June 21 release

.github/workflows/labeler.yml, content/en/docs/architecture/_index.md, content/en/docs/capacity/performance_tests_settings.md, content/en/docs/install/_index.md, content/en/docs/install/backup-recovery.md, content/en/docs/install/helm-parameters.md, content/en/docs/metrics.md, content/en/docs/relnotes/20210618_streams_relnotes.md
Merge documentation of June21 release to master.
=> June21 release (2.0.0 GA)

content/en/docs/_index.md, content/en/docs/architecture/_index.md, content/en/docs/quickstart.md
https://deploy-preview-107--streams-open-docs.netlify.app/docs/
https://deploy-preview-107--streams-open-docs.netlify.app/docs/quickstart/
https://deploy-preview-107--streams-open-docs.netlify.app/docs/architecture/
**Overall review**
- Main page
- Quick start
- Concepts
- Part of Reference Architecture
=> RMF-174 Streams Overall review

content/en/docs/architecture/_index.md, content/en/docs/relnotes/20210531_streams_relnotes.md, content/en/docs/relnotes/20210618_streams_relnotes.md, content/en/docs/relnotes/20210820_streams_relnotes.md
Update MariaDB Docker image to fix CVE-2021-3541.
=> STREAMS-2120 Update MariaDB Docker image to fix CVE-2021-3541 and create August 2021 Release Notes

content/en/docs/architecture/_index.md, content/en/docs/relnotes/20210820_streams_relnotes.md
https://deploy-preview-109--streams-open-docs.netlify.app/docs/architecture/#nginx
=> STREAMS-2132 Update nginx version

content/en/docs/relnotes/20210827_streams_relnotes.md, content/en/docs/subscribers/_index.md, content/en/docs/subscribers/subscriber-kafka.md, content/en/docs/subscribers/subscriber-sse.md, content/en/docs/subscribers/subscriber-webhook.md, content/en/docs/subscribers/subscriber-websocket.md
https://deploy-preview-111--streams-open-docs.netlify.app/docs/subscribers/subscriber-websocket
=> STREAMS-2177 add websocket subscriber documentation

content/en/docs/architecture/_index.md
https://deploy-preview-113--streams-open-docs.netlify.app/docs/architecture/#kafka
Upgrade the revision of kafka docker image
=> STREAMS-2173 upgrade kafka version

content/en/docs/architecture/_index.md
Add a paragraph to explain how to encrypt Kafka data at rest.
=> STREAMS-1868 explain how to encrypt Kafka data at rest

content/en/docs/install/upgrade.md
Add a caution note to do a backup before upgrade.
https://deploy-preview-116--streams-open-docs.netlify.app/docs/install/upgrade/
=> STREAMS-2203 - Add a caution note to do a backup before upgrade

content/en/docs/architecture/_index.md, content/en/docs/relnotes/20211130_streams_relnotes.md
https://deploy-preview-117--streams-open-docs.netlify.app/docs/architecture/
https://deploy-preview-117--streams-open-docs.netlify.app/docs/relnotes/20211130_streams_relnotes/
Update version of mariadb docker image and kafka revision
=> STREAMS-2178 Create release notes page for Nov 21, update Maria DB version and revision of kafka 2.8.0

content/en/docs/relnotes/20210827_streams_relnotes.md, content/en/docs/relnotes/20211130_streams_relnotes.md
https://deploy-preview-120--streams-open-docs.netlify.app/docs/relnotes/20210827_streams_relnotes/#streams-third-parties
=> Fix grammar and update template

content/en/docs/architecture/_index.md
https://deploy-preview-118--streams-open-docs.netlify.app/docs/architecture/
=> STREAMS-2206 doc(architecture): update third parties version

config.toml
For more information, see RMF-240
=> RMF-240 Update website title to remove the word Open

content/en/docs/publishers/publisher-http-poller.md
https://deploy-preview-125--streams-open-docs.netlify.app/docs/publishers/publisher-http-poller/
=> STREAMS-2250 Add pagination section

content/en/docs/install/_index.md, content/en/docs/install/helm-parameters.md
Switch registry from Dockerhub to Axway registry.
=> STREAMS-2223 Amplify registry

content/en/docs/install/_index.md, content/en/docs/relnotes/20211130_streams_relnotes.md
=> STREAMS-2322 Update kafka version and update installation documentation accordingly

content/en/docs/install/_index.md, content/en/docs/install/helm-parameters.md, content/en/docs/relnotes/20211130_streams_relnotes.md
1. Fix some incorrect default helm parameter value for:
- "*.replicaCount" is 1 in case of non-HA Streams installation
- "subscriberKafka.enabled" and "publisherKafka.enabled" are disabled by default. 
https://deploy-preview-130--streams-open-docs.netlify.app/docs/install/helm-parameters/#streams-parameters
2. Update release note for november release
https://deploy-preview-130--streams-open-docs.netlify.app/docs/relnotes/20211130_streams_relnotes/#important-changes
3. Add detailed steps to create a Service Account during installation (docker registry section)
https://deploy-preview-130--streams-open-docs.netlify.app/docs/install/#docker-registry-settings
4. Add details to download helm chart from support portal …
=> Prepare release november21

config.toml, content/en/docs/architecture/_index.md, content/en/docs/install/_index.md, content/en/docs/install/helm-parameters.md, content/en/docs/publishers/publisher-http-poller.md, content/en/docs/relnotes/20210827_streams_relnotes.md, content/en/docs/relnotes/20211130_streams_relnotes.md, content/en/docs/security/_index.md, content/en/docs/security/security-guide.md, content/en/docs/subscribers/subscriber-webhook.md
=> November21 release 2.0.7

.gitignore, content/en/docs/install/_index.md, content/en/docs/install/backup-recovery.md, content/en/docs/install/customize-install.md, content/en/docs/install/helm-parameters-reference.md, content/en/docs/install/uninstall.md, content/en/docs/install/upgrade.md, content/en/docs/metrics.md, content/en/docs/relnotes/20211130_streams_relnotes.md
https://deploy-preview-132--streams-open-docs.netlify.app/docs/install/customize-install/
=> STREAMS-2399 Add alternate installation settings section

content/en/docs/install/customize-install.md
=> STREAMS-2399 Add heading to manage helm parameters

content/en/docs/install/_index.md
Describe how to perform post install smoke tests to validate that Streams is properly installed and running.
https://deploy-preview-133--streams-open-docs.netlify.app/docs/install/#validate-the-installation
=> STREAMS-1415 - Describe how to run smoke tests after the installation

content/en/docs/publishers/publisher-http-poller.md, content/en/docs/publishers/publisher-http-post.md
https://deploy-preview-135--streams-open-docs.netlify.app/docs/publishers/publisher-http-poller/
Update section in publisher http poller about new attribute initialValue.
=> STREAMS-2330 add initialValue section

config.toml
Reverts Axway/streams-open-docs#139
For more information, see RMF-270
=> Revert "RDAPI-26352 and RMF-269 Update Docsy theme"

config.toml
This reverts commit 49dfd1a659dbf7c8077aa229d4a5cc809a89a547
For more information, see RMF-269.
=> Revert "Update Docsy theme (#139)" in the develop branch

content/en/docs/install/_index.md, content/en/docs/install/test-with-docker-compose.md, content/en/docs/install/upgrade.md
https://deploy-preview-137--streams-open-docs.netlify.app/docs/install/test-with-docker-compose/
=> STREAMS-2399 Missing docker compose section

content/en/docs/publishers/publisher-http-poller.md
https://deploy-preview-138--streams-open-docs.netlify.app/docs/publishers/publisher-http-poller/
Add details on initialValue behaviour in HTTP poller publisher
=> STREAMS-2330 doc(): add details on initialValue behaviour

content/en/docs/architecture/_index.md, content/en/docs/install/_index.md, content/en/docs/relnotes/20220228_streams_relnotes.md
Nginx ingress controller migration to version 1.1.1
https://deploy-preview-144--streams-open-docs.netlify.app/docs/install/
https://deploy-preview-144--streams-open-docs.netlify.app/docs/relnotes/20220228_streams_relnotes/
https://deploy-preview-144--streams-open-docs.netlify.app/docs/architecture/#nginx
=> nginx migration to 1.1.1

content/en/docs/install/_index.md, content/en/docs/install/helm-parameters-reference.md, content/en/docs/install/test-with-docker-compose.md, content/en/docs/relnotes/20220228_streams_relnotes.md, content/en/docs/subscribers/_index.md
Final documentation fixes and release note update to deliver the February 22 release.
Fixing specifically:
- https://jira.axway.com/browse/STREAMS-2484: Incorrect docker login url (same issue with the k8s image pull secret)
- https://jira.axway.com/browse/STREAMS-2537: Simplifying the use of image pull secrets for customer by providing a default name (which he is unlikely to care to change), thus sidestepping the need to describe how to modify arrays
- release note improvements
Preview links:
- https://deploy-preview-146--streams-open-docs.netlify.app/docs/install/
- https://deploy-preview-146--streams-open-docs.netlify.app/docs/install/test-with-docker-compose/
- …
=> Prepare release feb 22

.gitignore, content/en/docs/architecture/_index.md, content/en/docs/install/_index.md, content/en/docs/install/backup-recovery.md, content/en/docs/install/customize-install.md, content/en/docs/install/helm-parameters-reference.md, content/en/docs/install/test-with-docker-compose.md, content/en/docs/install/uninstall.md, content/en/docs/install/upgrade.md, content/en/docs/metrics.md, content/en/docs/publishers/publisher-http-poller.md, content/en/docs/publishers/publisher-http-post.md, content/en/docs/publishers/publisher-kafka.md, content/en/docs/publishers/publisher-sfdc.md, content/en/docs/relnotes/20211130_streams_relnotes.md, content/en/docs/relnotes/20220228_streams_relnotes.md, content/en/docs/subscribers/_index.md, content/en/docs/subscribers/subscriber-webhook.md
=> Test romain - February22 release 2.0.12

.gitignore, content/en/docs/architecture/_index.md, content/en/docs/install/_index.md, content/en/docs/install/backup-recovery.md, content/en/docs/install/customize-install.md, content/en/docs/install/helm-parameters-reference.md, content/en/docs/install/test-with-docker-compose.md, content/en/docs/install/uninstall.md, content/en/docs/install/upgrade.md, content/en/docs/metrics.md, content/en/docs/publishers/publisher-http-poller.md, content/en/docs/publishers/publisher-http-post.md, content/en/docs/publishers/publisher-kafka.md, content/en/docs/publishers/publisher-sfdc.md, content/en/docs/relnotes/20211130_streams_relnotes.md, content/en/docs/relnotes/20220228_streams_relnotes.md, content/en/docs/subscribers/_index.md, content/en/docs/subscribers/subscriber-webhook.md
Merging Develop branch into master for the February 2022 relase (version 2.0.12)
=> February22 release 2.0.12

config.toml
https://deploy-preview-150--streams-open-docs.netlify.app/docs/install/ - I can see the new design, and copy button is present
=> RMF-270 Update site with new version of Docsy theme

README.md, config.toml, layouts/_default/content.html, layouts/docs/list.html
* Update Readme file
*  Remove unnecessary section from pages
https://deploy-preview-151--streams-open-docs.netlify.app/docs/quickstart/
=> RMF-284 Update Readme and remove section from pages

content/en/docs/_index.md, i18n/en.toml, layouts/partials/page-meta-links.html
RMF-273
https://deploy-preview-153--streams-open-docs.netlify.app/docs
=> RMF-273 Remove links Create Issue and Contrib Guidelines from right-side menu

content/en/docs/architecture/_index.md, content/en/docs/relnotes/20220530_streams_relnotes.md
https://deploy-preview-154--streams-open-docs.netlify.app/docs/architecture/
https://deploy-preview-154--streams-open-docs.netlify.app/docs/relnotes/20220530_streams_relnotes/
Doc related to third party components upgrade for security fixes
=> STREAMS-2620 upgrade third party tags for security fixes

content/en/docs/install/_index.md, content/en/docs/install/amplify-central-integration.md, content/en/docs/install/helm-parameters-reference.md, content/en/docs/install/upgrade.md, content/en/docs/relnotes/20220530_streams_relnotes.md
Add operational documentation relevant to Streams Discovery Agent (new component of our product, that allows for integration with Amplify Central Catalog & Marketplace)
Fix a typo and misuse of a Helm command
Preview list:
* https://deploy-preview-158--streams-open-docs.netlify.app/docs/install/
* https://deploy-preview-158--streams-open-docs.netlify.app/docs/install/amplify-central-integration/
* https://deploy-preview-158--streams-open-docs.netlify.app/docs/install/helm-parameters-reference/
* https://deploy-preview-158--streams-open-docs.netlify.app/docs/relnotes/20220530_streams_relnotes/
* https://deploy-preview-158--streams-open-docs.netlify.app/docs/install/#use-amplify-platform-as-your-docker-registry
Before …
=> STREAMS-2435 Integration with Amplify Central Marketplace

content/en/docs/architecture/_index.md, content/en/docs/relnotes/20220630_streams_relnotes.md
Update documentation to reflect zookeeper version upgrade.
https://deploy-preview-161--streams-open-docs.netlify.app/docs/relnotes/20220630_streams_relnotes/
https://deploy-preview-161--streams-open-docs.netlify.app/docs/architecture/
=> STREAMS-2373 upgrade zookeeper version

content/en/docs/install/_index.md, content/en/docs/install/apim-integration.md, content/en/docs/install/customize-install.md
Describe how to secure Streams Hub and Subscribers APIs with APIM. 
https://deploy-preview-163--streams-open-docs.netlify.app/docs/install/apim-integration
https://deploy-preview-163--streams-open-docs.netlify.app/docs/install/customize-install/#activate-subscriber-sse-security
=> STREAMS-2699 integration with APIM

content/en/docs/install/apim-integration.md, content/en/docs/publishers/_index.md, content/en/docs/publishers/publisher-http-poller.md, content/en/docs/publishers/publisher-http-post.md, content/en/docs/subscribers/subscriber-kafka.md, content/en/docs/subscribers/subscriber-sse.md, content/en/docs/subscribers/subscriber-webhook.md, content/en/docs/topics-api.md
Documentation fix for BI
This refers notably to tickets STREAMS-2628 and STREAMS-2848
Added the following documentation:
-  the name of the frontend is important, that should be noted for operators https://deploy-preview-167--streams-open-docs.netlify.app/docs/install/apim-integration/#create-streams-front-end-apis
- document the 1MB limit and its possible responses https://deploy-preview-167--streams-open-docs.netlify.app/docs/publishers/#publication-size-limit
- explain the consolidation of the payload for http poller pagination https://deploy-preview-167--streams-open-docs.netlify.app/docs/publishers/publisher-http-poller/#pagination
- mention the API Gateway errors in possible generic API errors …
=> STREAMS-2848

content/en/docs/topics-api.md
http://pr-173.streams-open-docs.opendocs-builder.pcloud.axway.int/docs/topics-api/
=> RMF-381 Testing alert colors
